### ISSUE TITLE
Can't remove an item that has never been added

### ISSUE THREAD

**Issue by knownasilya** [lytics/ember-data.model-fragments#84]
Using `store.createRecord` and then modifying the defaults. Upon save of the model I get this error:

> Can't remove an item that has never been added

The server response looks normal, but I get this error and the fragments disappear from my template view.

**Fragment**
```js
export default DS.ModelFragment.extend({
  key: attr('string'),
  name: attr('string'),
  description: attr('string'),
  kind: attr('string'),
  abilities: hasOneFragment('ability', {
    defaultValue: {
      view: true
    }
  }),

  componentName: computed('kind', function () {
    const kind = this.get('kind');
    return `permission-${kind}`;
  })
});
```

It seems like it thinks that `abilities` is an array that was changed..

**Stack Trace**

```no-highlight
Uncaught Error: Can't remove an item that has never been added.
(anonymous function) @ ember.debug.js:34134
SubArray._findOperation @ ember.debug.js:34159
SubArray.removeItem @ ember.debug.js:34122
options.removedItem @ ember.debug.js:26075
DependentArraysObserver.flushChanges @ ember.debug.js:25267
DependentArraysObserver.itemPropertyDidChange @ ember.debug.js:25251
DependentArraysObserver.createPropertyObserver.observerContext.observer @ ember.debug.js:25118
apply @ ember.debug.js:18092
sendEvent @ ember.debug.js:12432
ObserverSet.flush @ ember.debug.js:14801
endPropertyChanges @ ember.debug.js:15533
notifyProperties @ ember-data.model-fragments.js:1293
CoreModel.extend.setupData @ ember-data.model-fragments.js:1189
(anonymous function) @ ember-data.model-fragments.js:209
map @ ember.debug.js:11793
StatefulArray.extend._processData @ ember-data.model-fragments.js:194
Ember.ArrayProxy.extend.setupData @ ember-data.model-fragments.js:435
(anonymous function) @ ember-data.model-fragments.js:749
ComputedPropertyPrototype.get @ ember.debug.js:10404
get @ ember.debug.js:15664get @ ember.debug.js:24962
(anonymous function) @ ember.debug.js:25423
forEach @ ember.debug.js:11807
(anonymous function) @ ember.debug.js:25419
DependentArraysObserver.suspendArrayObservers @ ember.debug.js:25056
recompute @ ember.debug.js:25418
Queue.invoke @ ember.debug.js:869
Queue.flush @ ember.debug.js:936
DeferredActionQueues.flush @ ember.debug.js:741
Backburner.end @ ember.debug.js:166
Backburner.run @ ember.debug.js:221
run @ ember.debug.js:15972
ember$data$lib$system$adapter$$Adapter.extend.ajax.Ember.RSVP.Promise.hash.success @ rest-adapter.js:784
jQuery.Callbacks.fire @ jquery.js:3143
jQuery.Callbacks.self.fireWith @ jquery.js:3255
done @ jquery.js:9309
jQuery.ajaxTransport.send.callback @ jquery.js:9713
XMLHttpRequest.send (async)jQuery.ajaxTransport.send @ jquery.js:9659
jQuery.extend.ajax @ jquery.js:9210
ember$data$lib$system$adapter$$Adapter.extend.ajax @ rest-adapter.js:792
initializePromise @ ember.debug.js:47024
Promise @ ember.debug.js:48652
ember$data$lib$system$adapter$$Adapter.extend.ajax @ rest-adapter.js:776
ember$data$lib$system$adapter$$Adapter.extend.createRecord @ rest-adapter.js:532
ember$data$lib$system$store$$_commit @ store.js:2014
(anonymous function) @ store.js:1270
forEach @ ember.debug.js:11807
ember$data$lib$system$store$$Service.extend.flushPendingSave @ store.js:1252
Queue.invoke @ ember.debug.js:871
Queue.flush @ ember.debug.js:936
DeferredActionQueues.flush @ ember.debug.js:741
Backburner.end @ ember.debug.js:166
Backburner.run @ ember.debug.js:221
run @ ember.debug.js:15972
handleRegisteredAction @ ember.debug.js:18481
(anonymous function) @ ember.debug.js:38175
jQuery.event.dispatch @ jquery.js:4665
jQuery.event.add.elemData.handle
```

**Comment by knownasilya** [comment]
If I visit the saved model later, it has the correct values, but editing/saving and creating new/saving has this same result.

**Comment by knownasilya** [comment]
Found it, I have a computed property and it's trying to parse it on the fragment..

**Comment by slindberg** [comment]
I'm not sure I understand what's going on here, is this a model fragments issue, or were you overriding the fragment property by mistake? As usual, a jsbin is the best way for me to diagnose.

**Comment by slindberg** [comment]
If you are ever able to reproduce this behavior in a failing test, jsbin, etc. please reopen.

**Comment by louy** [comment]
I think the issue is caused by having a computed property on a fragment. Is this a known bug?

**Comment by knownasilya** [comment]
That's a good point.. I did have a CP.

**Comment by slindberg** [comment]
I think this was happening because fragments that were accessed prior to the save didn't get updated with the new data until after they are accessed again. This also only happens when the adapter returns a response with data in it, instead of a `204`. It should be fixed by #109, [here's the relevant test](https://github.com/lytics/ember-data.model-fragments/commit/a8b2d5ff81b7cb64f93cfb4760d4105e2a52968c).

**Comment by knownasilya** [comment]
Is this still an issue in the 0.3.x series?

**Comment by slindberg** [comment]
Shouldn't be, just forgot to close

**Comment by knownasilya** [comment]
So this is still an issue in 0.3.3, 204 solves it kind, but introduces an issue where you have fragments that aren't updated after save, since the new data isn't send back, so the model isn't updated.

**Comment by knownasilya** [comment]
And passing data with the 204 doesn't help.

**Comment by knownasilya** [comment]
Is there a way to set the data back on those items? Because the only workaround is a refresh of the page, and if you forget and save the model, you overwrite the data with blank fragments.

**Comment by knownasilya** [comment]
@slindberg would love your thoughts on this.

**Comment by slindberg** [comment]
> So this is still an issue in 0.3.3, 204 solves it kinda, but introduces an issue where you have fragments that aren't updated after save, since the new data isn't send back, so the model isn't updated.

This issue is fixed in v0.4.0, which is tied to ED >= v1.13.0. Unfortunately I don't have the spare cycles to try to backport this fix to a v0.3.x series release, since the fix was a byproduct of refactoring adapter updates for v1.13 compatibility. I think your only option right now is to update ED :confused: 

-------------

For clarity's sake and for future readers of this issue, there are two ways an API can respond to a POST/PUT/PATCH<sup>1</sup>:

1. `200 OK` - Contains a data payload. ED treats this new data payload as canonical, and MF should respect that (if it doesn't, it's a bug).
2. `204 No Content` - Does not contain data payload. ED assumes that the current state of the model is now canonical, and simply transitions to a clean state. MF should also respect this.

So if your server needs to update properties on the model (e.g. update a `modified` timestamp), you must use the first approach. If the server also modifies fragments, the objects will be updated to reflect the new state.

The issue was that when the adapter responds with a payload, existing fragments/arrays were not notified of the update, so they ended up returning stale data. As I said, this should be fixed in v0.4.0.

<sup>[1]</sup> Note that the actual HTTP response code does not matter (as long as it's a 2XX), it's simply convention.
